In [58]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [59]:
import numpy as np

In [60]:
grades =[[85, 78, 92, 88],
[70, 76, 80, 65],
[90, 88, 94, 91],
[60, 65, 58, 62],
[100, 95, 98, 97]] 

In [61]:
grades_array = np.array(grades)

In [62]:
np.shape(grades)

(5, 4)

### احسب متوسط درجات الطلاب امشي بشكل افقي

In [71]:
mean_stu=np.mean(grades,axis=1)
print(mean_stu)

[85.75 72.75 90.75 61.25 97.5 ]


### احسب متوسط درجات الطلاب امشي بشكل رأسي

In [69]:
mean_sub=np.mean(grades,axis=0)
print(mean_sub)

[81.  80.4 84.4 80.6]


In [65]:
top_stu = grades_array[mean_stu > 85]
print(top_stu)

[[ 85  78  92  88]
 [ 90  88  94  91]
 [100  95  98  97]]
